# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1f8932fc9a7a048231d84a91b22f1c95e39943a9c69849299c622f6eb6bcb2b608c2e8dc7689a9bcb5ac0d87e8710e89d410406609ae352ade6a4f102397821

test:
  secret_key_base: 686a760da651237b13b0bdebb9453583f3c2adbecb175de91ff4d9a28bbd054688726d9260a84357801e3d816842be00fdbd32d7918c76e035cf59342afae922

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
